"use client"

/**
 * Formats the content for download with proper headers and spacing
 */
function formatContent(title, content, summary) {
  const separator = '='.repeat(80);
  const date = new Date().toLocaleDateString('en-IN');

  return `INDIAN LEGAL DIGEST
${separator}

CASE: ${title}
DATE EXPORTED: ${date}

${separator}
FULL JUDGMENT
${separator}

${content}

${separator}
SUMMARY
${separator}

${summary}

${separator}
Generated by Indian Legal Digest
Copyright © ${new Date().getFullYear()} Indian Legal Digest. All rights reserved.`;
}

/**
 * Utility function to download content as a text file
 */
export function downloadAsTextFile(filename, content) {
  const element = document.createElement('a');
  const file = new Blob([content], { type: 'text/plain;charset=utf-8' });

  element.href = URL.createObjectURL(file);
  element.download = filename;

  // Ensure proper cleanup
  const cleanup = () => {
    document.body.removeChild(element);
    URL.revokeObjectURL(element.href);
  };

  document.body.appendChild(element);
  element.click();

  // Clean up after the download starts
  setTimeout(cleanup, 100);
}

// Optional: Export the formatter if needed elsewhere
export { formatContent };
